# It's necessary to set this because some environments don't link sh -> bash.
SHELL := /bin/bash


build:
	@echo "Building site"
	hugo --destination ../


devel:
	@echo "Running local development server"
	hugo server --disableFastRender -D
